---
- name: Playbook para criar usuário 'loja', configurar login automático e desativar bloqueio de tela no RHEL
  hosts: all
  become: yes
  tasks:

    - name: Criar usuário 'loja' sem senha
      user:
        name: loja
        state: present


    - name: Criar seção [daemon] no arquivo custom.conf, se não existir
      lineinfile:
        path: /etc/gdm/custom.conf
        line: '[daemon]'
        insertafter: '^# GDM configuration storage'
        create: yes

    - name: Configurar GDM para login automático do usuário 'loja'
      lineinfile:
        path: /etc/gdm/custom.conf
        insertafter: '^\[daemon\]'
        regexp: '^AutomaticLoginEnable='
        line: 'AutomaticLoginEnable=True'

    - name: Configurar usuário automático no GDM
      lineinfile:
        path: /etc/gdm/custom.conf
        insertafter: '^\[daemon\]'
        regexp: '^AutomaticLogin='
        line: 'AutomaticLogin=loja'


    - name: Desativar bloqueio de tela por inatividade no GNOME
      become_user: loja
      dconf:
        key: /org/gnome/desktop/screensaver/lock-enabled
        value: 'false'

  handlers:
    - name: restart_gdm
      systemd:
        name: gdm
        state: restarted

